version: '2'

services:

  application:
    image: tianon/true
    volumes:
      - ../:/var/www

  qm_workspace:
    build:
      context: ./workspace
      args:
        - PUID=1000
        - PGID=1000
        - TZ=UTC
    volumes_from:
      - application
    tty: true

  qm_php-fpm:
    build:
      context: ./php-fpm
    volumes_from:
      - application
    expose:
      - "9000"
    links:
      - qm_workspace

  qm_nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=qm_php-fpm
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    links:
      - qm_php-fpm

  qm_db:
    build:
      context: ./postgres
    environment:
      - POSTGRES_DB=queryme
      - POSTGRES_USER=queryme
      - POSTGRES_PASSWORD=queryme
    volumes:
      - qm_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  qm_db:
    driver: "local"
